### ISSUE TITLE
New installation :  mirror does not support the specified release (wheezy)

### ISSUE THREAD

**Issue by Shnoulle** [YunoHost/rebuildd#1]
Hi,

yesterday, starting a new installation with yunohostv2-latest-amd64.iso, unable to finalize it.

When trying to get the mirror: always have "repo broken". Looking at console:
`WARNING **: mirror does not support the specified release (wheezy)`

yunohost 2.2 seems to be jessie compatible ( https://github.com/YunoHost/install_script/commit/1b0aecc5b9e0049cbc6bf42ac31ce6212c2a4c70 ) ? Then maybe doing a iso for 2.2 is OK ?

Thanks

**Comment by jeromelebleu** [comment]
This is the wrong repository for this question... If you still have this issue - I hope for you not since the time! - please open a new ticket [here](https://dev.yunohost.org).
